// Code generated by entc, DO NOT EDIT.

package tenant

import (
	"time"
)

const (
	// Label holds the string label denoting the tenant type in the database.
	Label = "tenant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// EdgeConn holds the string denoting the conn edge name in mutations.
	EdgeConn = "conn"
	// Table holds the table name of the tenant in the database.
	Table = "tenants"
	// ConnTable is the table that holds the conn relation/edge.
	ConnTable = "tenant_conns"
	// ConnInverseTable is the table name for the TenantConn entity.
	// It exists in this package in order to avoid circular dependency with the "tenantconn" package.
	ConnInverseTable = "tenant_conns"
	// ConnColumn is the table column denoting the conn relation/edge.
	ConnColumn = "tenant_conn"
)

// Columns holds all SQL columns for tenant fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldName,
	FieldDisplayName,
	FieldRegion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)
