// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"github.com/go-saas/saas/examples/ent/tenant/ent/post"
	"github.com/go-saas/saas/examples/ent/tenant/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postMixin := schema.Post{}.Mixin()
	postMixinHooks0 := postMixin[0].Hooks()
	post.Hooks[0] = postMixinHooks0[0]
	postMixinInters0 := postMixin[0].Interceptors()
	post.Interceptors[0] = postMixinInters0[0]
}

const (
	Version = "v0.12.4"                                         // Version of ent codegen.
	Sum     = "h1:LddPnAyxls/O7DTXZvUGDj0NZIdGSu317+aoNLJWbD8=" // Sum of ent codegen.
)
