// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TenantConn is the predicate function for tenantconn builders.
type TenantConn func(*sql.Selector)
